# Documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'Dependency Updates'
    ignore:
      # For Eslint, ignore all Dependabot updates for version 9 until supported by peer dependencies (typescript-eslint)
      - dependency-name: 'eslint'
        versions: ['9.x']
        # For d3-dsv, ignore all Dependabot updates for version 3 until supported by peer dependencies (langchain)
      - dependency-name: 'd3-dsv'
        versions: ['3.x']
    groups:
      # group dev dependencies together in a single pull request
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - '@eslint*'
          - '@swc*'
          - '@types*'
          - 'eslint*'
          - 'jest'
          - 'prettier'
          - 'ts-*'
          - 'typescript*'
      dev-dependencies-security-updates:
        applies-to: security-updates
        patterns:
          - '@eslint*'
          - '@swc*'
          - '@types*'
          - 'eslint*'
          - 'jest'
          - 'prettier'
          - 'ts-*'
          - 'typescript*'
      # group Genkit related updates in a single pull request
      genkit:
        applies-to: version-updates
        patterns:
          - '@genkit*'
          - 'genkit*'
      genkit-security-updates:
        applies-to: security-updates
        patterns:
          - '@genkit*'
          - 'genkit*'
      # group langchain related updates in a single pull request
      langchain:
        applies-to: version-updates
        patterns:
          - '@langchain*'
          - 'langchain'
          - 'd3-dsv' # used for data loading by langchain for CSV
      langchain-security-updates:
        applies-to: security-updates
        patterns:
          - '@langchain*'
          - 'langchain'
          - 'd3-dsv' # used for data loading by langchain for CSV
      # group rest of the dependencies together
      dependencies:
        applies-to: version-updates
        patterns:
          - 'dotenv'
          - 'firebase-admin'
          - 'zod'
      dependencies-security-updates:
        applies-to: security-updates
        patterns:
          - 'dotenv'
          - 'firebase-admin'
          - 'zod'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'GitHub Actions Updates'
